---
name: POE-Component-IRC-Plugin-WWW-Lipsum
version: 0.0103
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: plugin to generate Lorem Ipsum text in IRC
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  POE::Component::IRC::Plugin::BasePoCoWrap: 0.004
  POE::Component::WWW::Lipsum: 0.0102
build_requires:
  Test::More: 0
provides:
  POE::Component::IRC::Plugin::WWW::Lipsum:
    file: lib/POE/Component/IRC/Plugin/WWW/Lipsum.pm
    version: 0.0103
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
